- name: Add zeal ppa

  become: true
  remote_user: root

  apt_repository:
    repo: "ppa:zeal-developers/ppa"

- name: Install zeal

  become: true
  remote_user: root

  apt:
    name: zeal
    update_cache: yes
