- name: Install java

  become: true
  remote_user: root

  apt:
    name:
      - openjdk-11-jdk
      - openjdk-11-demo
      - openjdk-11-doc
      - openjdk-11-jre-headless
      - openjdk-11-source

    update_cache: yes

- name: Install build tools

  become: true
  remote_user: root

  apt:
    name:
      - gradle
      - maven

    update_cache: yes

- name: Install scala

  become: true
  remote_user: root
  apt:
    name:
      - scala

    update_cache: yes
