- name: Install java

  become: true
  remote_user: root

  apt:
    name:
      - openjdk-11-jdk
      - openjdk-11-demo
      - openjdk-11-doc
      - openjdk-11-jre-headless
      - openjdk-11-source
      
    update_cache: yes
