- name: Add ansible ppa

  become: true
  remote_user: root

  apt_repository:
    repo: "ppa:ansible/ansible"

- name: Install ansible

  become: true
  remote_user: root

  apt:
    name:
      - ansible
      - python-pip
    update_cache: yes

- name: Install ansible-lint
  become: true
  remote_user: root

  pip:
    name: ansible-lint
